### ISSUE TITLE
Background color on headings makes it hard to read in dark mode

### ISSUE THREAD

**Issue by pawamoy** [athena-framework/website#6]
![image](https://user-images.githubusercontent.com/3999221/105020253-5af33c00-5a47-11eb-9b36-3e375b3fdd6e.png)

Hey @oprypin, I was stalking your work again and found this 🙂

**Comment by oprypin** [comment]
Obsoleted by #5

**Comment by Blacksmoke16** [comment]
Fixed by #5.
